-- ============================================================
-- AI Marketing Workspace — full schema (through migration 0024)
-- Generated by concatenating the structural migrations in order.
-- Source of truth is migrations/*.sql — if you edit the schema,
-- edit the numbered migration file and regenerate this, not the
-- other way around.
-- 
-- Paste this whole file into Supabase Dashboard → SQL Editor and
-- run it once. Then run seed.sql. See supabase/README.md.
-- 
-- Already applied an earlier version of this file? You only need
-- the new part — see "If you already applied an earlier version"
-- in supabase/README.md for the exact migrations per stage.
-- ============================================================

-- ---------- migrations/0001_extensions_and_helpers.sql ----------
-- Stage 3: extensions and shared helpers used by every later migration.

-- UUID generation for primary keys.
create extension if not exists "pgcrypto" with schema extensions;

-- Generic "bump updated_at on every UPDATE" trigger helper, ships with
-- Supabase Postgres. Used instead of a hand-rolled trigger function so
-- every table gets identical, well-tested behavior.
create extension if not exists "moddatetime" schema extensions;

-- ---------- migrations/0002_plans_and_plan_limits.sql ----------
-- Plans and their limits. Created before `users` (migration 3) because
-- `users.plan_id` references `plans(id)` — reference/billing tables have
-- to exist before anything that points at them.

create table public.plans (
  id uuid primary key default extensions.gen_random_uuid(),
  slug text not null unique check (slug in ('free', 'pro', 'enterprise')),
  name text not null,
  price_month numeric(10, 2) check (price_month is null or price_month >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.plans
  for each row execute procedure extensions.moddatetime(updated_at);

create table public.plan_limits (
  id uuid primary key default extensions.gen_random_uuid(),
  plan_id uuid not null unique references public.plans(id) on delete cascade,
  -- null = unlimited, in every *_per_month / max_* column below.
  max_generations_per_month integer check (max_generations_per_month is null or max_generations_per_month >= 0),
  max_saved_results integer check (max_saved_results is null or max_saved_results >= 0),
  max_company_profiles integer default 1 check (max_company_profiles is null or max_company_profiles >= 1),
  -- "all" (jsonb string) or a jsonb array of tool/model slugs.
  allowed_tool_ids jsonb not null default '"all"'::jsonb,
  allowed_ai_models jsonb not null default '"all"'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.plan_limits
  for each row execute procedure extensions.moddatetime(updated_at);

-- Reference/pricing data — safe to expose to anyone, logged in or not
-- (a pricing page needs this before signup). No write policies: plans and
-- their limits are only ever changed by hand in the SQL editor or by a
-- future admin tool, never by application code.
alter table public.plans enable row level security;
alter table public.plan_limits enable row level security;

create policy "plans are publicly readable"
  on public.plans for select
  to anon, authenticated
  using (is_active = true);

create policy "plan_limits are publicly readable"
  on public.plan_limits for select
  to anon, authenticated
  using (true);

-- ---------- migrations/0003_users.sql ----------
-- Mirrors auth.users 1:1. Supabase's own auth.users table is in a
-- protected schema the client can't query under RLS in a useful way, and
-- we need a place to hang app-specific columns (plan_id) and a stable
-- `public` row for every FK in the rest of the schema to point at.
--
-- Populated by a trigger on auth.users (migration 0009, after every table
-- it touches — plans and subscriptions — exists), not here.

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  plan_id uuid references public.plans(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index users_plan_id_idx on public.users(plan_id);

create trigger set_updated_at
  before update on public.users
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.users enable row level security;

-- A user can see and edit their own row only. There is deliberately no
-- INSERT policy — rows are created exclusively by the `handle_new_user`
-- trigger (SECURITY DEFINER, migration 0009), never by client code, so a
-- signed-in user can never insert an arbitrary row for another id.
create policy "users can view own row"
  on public.users for select
  to authenticated
  using (auth.uid() = id);

create policy "users can update own row"
  on public.users for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ---------- migrations/0004_company_profiles.sql ----------
-- One user can hold more than one company profile (agencies managing
-- several clients — see plan_limits.max_company_profiles and the project
-- architecture doc §11 "not rushing team roles into MVP, but the schema
-- should allow it"). No uniqueness constraint on user_id: that's the
-- concrete expression of that decision.

create table public.company_profiles (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  niche text,
  tone_of_voice text,
  target_audience text,
  usp text,
  website_url text,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index company_profiles_user_id_idx on public.company_profiles(user_id);

create trigger set_updated_at
  before update on public.company_profiles
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.company_profiles enable row level security;

-- Full CRUD scoped to the owning user — Stage 12 (Company Profile screen)
-- can read/write this directly from a Server Action or the browser client
-- without a dedicated API route; RLS is the only gate it needs.
create policy "users can view own company profiles"
  on public.company_profiles for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert own company profiles"
  on public.company_profiles for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can update own company profiles"
  on public.company_profiles for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete own company profiles"
  on public.company_profiles for delete
  to authenticated
  using (auth.uid() = user_id);

-- ---------- migrations/0005_guest_sessions.sql ----------
-- Guest sessions have no auth.uid() to key RLS off of — a guest is, by
-- definition, not authenticated. Rather than build a workaround (e.g.
-- trusting a session_token passed as a query param, which anyone could
-- guess or intercept), this table gets RLS enabled with NO policies at
-- all: that makes it default-deny for both `anon` and `authenticated`
-- roles, full stop. The only way in is the service-role key, which
-- bypasses RLS entirely and is only ever used from trusted server code
-- (Stage 5's /api/generate, Stage 11's merge logic) — never shipped to
-- the browser. This is the safest option available for unauthenticated
-- state, not a placeholder to revisit.

create table public.guest_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  session_token text not null unique,
  company_profile_draft jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

-- Session_token lookups (every read) and the TTL cleanup job (Stage 5+)
-- both need their own index; the unique constraint above already gives
-- session_token one for free.
create index guest_sessions_expires_at_idx on public.guest_sessions(expires_at);

create trigger set_updated_at
  before update on public.guest_sessions
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.guest_sessions enable row level security;
-- No policies — see comment above.

-- ---------- migrations/0006_tools_and_templates.sql ----------
-- Reference data that drives the whole "add a tool = a config row, not a
-- deploy" mechanism (project architecture doc §7/§14). Public read-only —
-- both guests and signed-in users need to see the Tools Gallery and
-- Templates Library before/without registering.

create table public.tools (
  id uuid primary key default extensions.gen_random_uuid(),
  slug text not null unique,
  name text not null,
  config_schema jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.tools
  for each row execute procedure extensions.moddatetime(updated_at);

create table public.templates (
  id uuid primary key default extensions.gen_random_uuid(),
  tool_id uuid not null references public.tools(id) on delete cascade,
  slug text not null unique,
  name text not null,
  category text not null,
  prompt_template text not null default '',
  required_fields jsonb not null default '[]'::jsonb,
  is_premium boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index templates_tool_id_idx on public.templates(tool_id);
create index templates_category_idx on public.templates(category);

create trigger set_updated_at
  before update on public.templates
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.tools enable row level security;
alter table public.templates enable row level security;

create policy "active tools are publicly readable"
  on public.tools for select
  to anon, authenticated
  using (is_active = true);

create policy "templates are publicly readable"
  on public.templates for select
  to anon, authenticated
  using (true);

-- No write policies on either table: managed by hand via the SQL editor
-- (or a future admin tool) only, per the "config, not code" principle —
-- application code only ever reads these.

-- ---------- migrations/0007_usage_and_subscriptions.sql ----------
-- Usage counters and billing status. Both are trusted-write-only: no
-- INSERT/UPDATE/DELETE policy exists for `authenticated` on either table.
-- If a client could increment its own usage_counters row, plan limits
-- would be decorative. Writes happen exclusively from server code using
-- the service-role client (Stage 5 for usage_counters on every
-- generation, a future Stripe webhook for subscriptions) — SELECT is
-- still open to the owning user so a usage indicator / billing page can
-- read this directly without a dedicated API route.

create table public.usage_counters (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  generations_count integer not null default 0 check (generations_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usage_counters_period_valid check (period_end > period_start),
  constraint usage_counters_user_period_unique unique (user_id, period_start)
);

create index usage_counters_user_id_idx on public.usage_counters(user_id);

create trigger set_updated_at
  before update on public.usage_counters
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.usage_counters enable row level security;

create policy "users can view own usage"
  on public.usage_counters for select
  to authenticated
  using (auth.uid() = user_id);

create table public.subscriptions (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  plan_id uuid not null references public.plans(id),
  status text not null default 'active'
    check (status in ('active', 'trialing', 'past_due', 'canceled')),
  provider_ref text,
  period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index subscriptions_user_id_idx on public.subscriptions(user_id);
create index subscriptions_status_idx on public.subscriptions(status);

create trigger set_updated_at
  before update on public.subscriptions
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.subscriptions enable row level security;

create policy "users can view own subscription"
  on public.subscriptions for select
  to authenticated
  using (auth.uid() = user_id);

-- ---------- migrations/0008_generations.sql ----------
-- The core event table every AI tool writes to. Owned by exactly one of
-- `user_id` / `guest_session_id` (enforced below), which is what makes
-- the guest→user merge (Stage 11) a metadata UPDATE rather than a data
-- copy: flipping guest_session_id to null and setting user_id on existing
-- rows is enough, nothing needs to move.

create table public.generations (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  guest_session_id uuid references public.guest_sessions(id) on delete cascade,
  company_profile_id uuid references public.company_profiles(id) on delete set null,
  tool_id uuid not null references public.tools(id),
  template_id uuid references public.templates(id) on delete set null,
  ai_provider text not null,
  ai_model text not null,
  input_params jsonb not null default '{}'::jsonb,
  output text not null default '',
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint generations_owner_required
    check (user_id is not null or guest_session_id is not null)
);

-- History screen (Stage 11) paginates a single user's rows newest-first —
-- this is the index that query actually needs.
create index generations_user_id_created_at_idx
  on public.generations(user_id, created_at desc);
create index generations_guest_session_id_idx on public.generations(guest_session_id);
create index generations_tool_id_idx on public.generations(tool_id);

create trigger set_updated_at
  before update on public.generations
  for each row execute procedure extensions.moddatetime(updated_at);

alter table public.generations enable row level security;

-- Scoped to the owning user. This is what lets Stage 5's /api/generate use
-- the caller's own session-bound Supabase client (RLS-enforced) for
-- signed-in requests instead of the service-role key — the privileged
-- client is reserved for guest requests, which have no auth.uid() to
-- scope a policy to (same reasoning as guest_sessions, migration 0005).
create policy "users can view own generations"
  on public.generations for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can insert own generations"
  on public.generations for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Scoped update, not just for "is_favorite": a client toggling one field
-- on its own row is a normal, safe operation under RLS, and adding this
-- now means Stage 11 (History screen, favorites) needs no new policy.
create policy "users can update own generations"
  on public.generations for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------- migrations/0009_auth_trigger.sql ----------
-- Auto-creates the public.users (+ starter subscription) row the moment
-- Supabase Auth creates an auth.users row — i.e. right after signUp()
-- (Stage 2). Defined last, not alongside `users` in migration 0003,
-- because it writes to `public.subscriptions`, which doesn't exist until
-- migration 0007 — a plpgsql function body isn't checked against table
-- existence at CREATE time, but the trigger still shouldn't be *live*
-- before every table it touches is.
--
-- SECURITY DEFINER: runs with the privileges of the function's owner
-- (postgres), not the invoking session — required because this fires
-- inside Supabase's own auth flow, before the new user has any session
-- for RLS to key off of.

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan_id uuid;
begin
  select id into v_plan_id from public.plans where slug = 'free' limit 1;

  insert into public.users (id, email, plan_id)
  values (new.id, new.email, v_plan_id);

  -- If the free plan hasn't been seeded yet, v_plan_id is null and the
  -- user is created with no plan rather than failing signup outright —
  -- degraded, not broken. Seeding (migration 0010) always runs before any
  -- real signup in practice, but the function doesn't assume it.
  if v_plan_id is not null then
    insert into public.subscriptions (user_id, plan_id, status)
    values (new.id, v_plan_id, 'active');
  end if;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------- migrations/0011_increment_usage_counter.sql ----------
-- Additive-only migration (Stage 5): one new function, no table changes.
-- Not a schema redesign — the architecture approved in Stage 3 is
-- untouched; this is the atomic-increment primitive that
-- lib/generation/save.ts needs to update usage_counters safely under
-- concurrent requests (two tabs, a client retry) without a lost update.
--
-- A select-then-update from application code has a race: two concurrent
-- requests can both read count=5, both write count=6, and one increment
-- is silently lost — exactly the kind of bug that's invisible in testing
-- and shows up as "my limit let me generate one more than it should have"
-- in production. This function does the read-modify-write as a single
-- atomic UPSERT instead.

create or replace function public.increment_usage_counter(
  p_user_id uuid,
  p_period_start date,
  p_period_end date
)
returns public.usage_counters
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.usage_counters;
begin
  insert into public.usage_counters (user_id, period_start, period_end, generations_count)
  values (p_user_id, p_period_start, p_period_end, 1)
  on conflict (user_id, period_start)
  do update set generations_count = public.usage_counters.generations_count + 1
  returning * into v_row;

  return v_row;
end;
$$;

-- SECURITY DEFINER functions are exposed via PostgREST (and therefore
-- callable by `anon`/`authenticated` through supabase-js .rpc()) by
-- default, same as any other schema object — that would let a signed-in
-- user call this directly and increment (or fabricate) their own usage
-- row from the client, defeating the entire point of usage_counters
-- having no client write policy (migration 0007). Explicitly revoking
-- from anon/authenticated and granting only to service_role closes that
-- gap; only the admin client (lib/supabase/admin.ts) can call this.
revoke all on function public.increment_usage_counter(uuid, date, date) from public, anon, authenticated;
grant execute on function public.increment_usage_counter(uuid, date, date) to service_role;

-- ---------- migrations/0012_tools_gallery_fields.sql ----------
-- Stage 7 (Tools Gallery) needs `tools.description`, `tools.icon`, and
-- `tools.category` for cards, categories, and search — none of which
-- existed in migration 0006. This wasn't an oversight to quietly patch:
-- Stage 6 (ToolRunner) genuinely never needed them, so they weren't added
-- until a real consumer (this stage) required them. Additive-only, same
-- discipline as migration 0011 — no existing column touched, nothing
-- Stage 1-6 depends on changes shape.
--
-- All three nullable: existing seed rows (migration 0010) predate these
-- columns, and a tool without a category/description/icon should degrade
-- gracefully in the gallery (see components/tools/gallery/ToolCard.tsx),
-- not be forced to backfill placeholder content it doesn't have yet.

alter table public.tools
  add column description text,
  add column icon text,
  add column category text;

-- Supports category filtering — in-memory today (Stage 7 scope: dataset
-- is a handful of tools), but this is exactly the kind of index that
-- costs nothing now and avoids a migration later if/when category
-- filtering moves server-side, per the project architecture doc's
-- general "cheap now, expensive later" indexing rationale (see the
-- Stage 3 audit for company_profiles/generations precedent).
create index tools_category_idx on public.tools(category);

-- ---------- migrations/0016_templates_config_and_premium.sql ----------
-- Stage 10 (completion): the three columns the Templates Library needs to
-- finish what the architecture doc describes and Stage 10 left open.
-- Additive only — no existing column, row, policy or migration changes.
--
-- 1. templates.config_schema — an optional per-template form. The
--    architecture doc (§12) has ToolRunner render "config_schema
--    инструмента/шаблона": a tool's form OR a template's. NULL — every
--    row that exists today — means "use the owning tool's form", so
--    nothing shipped in Stage 8/9 changes behavior. Needed because
--    platform/format-specific templates ask for different inputs than
--    their tool's general-purpose form: a "Facebook Ad" template has no
--    use for ad-generator's "Platform" select (and showing it would let a
--    person pick "Google Search" for a Facebook template), a cold email
--    needs "who you're writing to", an SEO article needs a target
--    keyword. Same format as tools.config_schema
--    (lib/tool-config/schema.ts), same parser, same fallback.
--
-- 2. templates.is_default — which template a tool page uses when no
--    `?template=` is given. Stage 8 picked "oldest by created_at" and
--    said explicitly that Stage 10 could introduce a real notion of
--    "default" once tools had several templates. They now do (0017), and
--    "oldest" stops being well-defined: when seed.sql runs in one
--    transaction (the Supabase SQL editor does that), every template of a
--    tool gets the same now(). At most one default per tool, enforced by
--    a partial unique index; lib/generation/catalog.ts still falls back to
--    the oldest template for a tool that has none flagged.
--
-- 3. plan_limits.premium_templates — whether a plan may use templates
--    flagged `templates.is_premium` (a column since Stage 3 that nothing
--    ever read). Architecture doc §18: Free gets the basic library, Pro
--    gets "вся библиотека шаблонов". A plan_limits column rather than a
--    `plan slug !== 'free'` check in code, for the same reason every other
--    entitlement lives in plan_limits (architecture doc §13 — limits are
--    data, not code). Defaults to false (fail closed); the data migration
--    that follows (0017) turns it on for Pro/Enterprise and flags the
--    defaults.

alter table public.templates
  add column config_schema jsonb;

alter table public.templates
  add column is_default boolean not null default false;

create unique index templates_one_default_per_tool_idx
  on public.templates(tool_id)
  where is_default;

alter table public.plan_limits
  add column premium_templates boolean not null default false;

-- ---------- migrations/0018_users_no_client_updates.sql ----------
-- Stage 15 (security): a signed-in user could change their own plan.
--
-- Migration 0003 gave `public.users` an owner-scoped UPDATE policy ("users
-- can update own row"). That row holds `plan_id`, so any signed-in user
-- could send `update users set plan_id = <enterprise>` through the public
-- API with their own session and grant themselves unlimited generations
-- and premium templates — found by the Stage 15 security pass against a
-- real Supabase stack. Nothing in the application writes this table from
-- a client (the signup trigger, migration 0009, is SECURITY DEFINER; plan
-- changes will come from the billing integration through the service
-- role), so the policy has no legitimate user.
--
-- Dropping the policy already makes client updates match no rows under
-- RLS; revoking the privilege as well turns an attempt into an explicit
-- permission error and keeps it closed even if a policy is re-added
-- carelessly later. Reads are unchanged ("users can view own row").

drop policy if exists "users can update own row" on public.users;

revoke update on public.users from anon, authenticated;

-- ---------- migrations/0019_client_privileges.sql ----------
-- Phase 2 (database): client roles keep only the privileges the app uses.
--
-- Supabase grants `anon` and `authenticated` every privilege on every
-- table in `public`; RLS then filters rows. That left three real gaps:
--
-- 1. `generations`: the owner could rewrite any column of their own rows
--    through the public API — output, tool, created_at (backdating rows
--    defeats the per-minute rate limit, lib/limits/rateLimit.ts). The app
--    only ever changes `is_favorite` from a user session
--    (app/(auth)/history/actions.ts).
-- 2. `generations` INSERT accepted any `guest_session_id`: a signed-in user
--    who knew a guest session's id could spend that guest's free allowance
--    (lib/limits/checkUsage.ts counts guest generations by that column).
--    Rows saved for a signed-in user never carry one (lib/generation/save.ts).
-- 3. Writes to server-only tables (plans, plan_limits, tools, templates,
--    usage_counters, subscriptions, guest_sessions) were only filtered by
--    RLS — an UPDATE or DELETE "succeeded" on zero rows instead of being
--    refused — and TRUNCATE, which RLS doesn't apply to, was still granted.
--
-- Server code uses the service role and is unaffected. The matrix below
-- is exactly what the application's user-session queries need; RLS
-- policies still decide which rows.

revoke all on table
  public.plans,
  public.plan_limits,
  public.tools,
  public.templates,
  public.users,
  public.company_profiles,
  public.guest_sessions,
  public.usage_counters,
  public.subscriptions,
  public.generations
from anon, authenticated;

-- Reference data: pricing, Tools Gallery, Templates Library — public.
grant select on public.plans, public.plan_limits, public.tools, public.templates
  to anon, authenticated;

-- A user's own account, usage and subscription: read-only.
grant select on public.users, public.usage_counters, public.subscriptions
  to authenticated;

-- Company profile: fully managed by its owner (app/(auth)/profile/actions.ts).
grant select, insert, update, delete on public.company_profiles to authenticated;

-- Generations: read and save own (lib/generation/save.ts); the only column
-- a user may change afterwards is the favorite flag.
grant select, insert on public.generations to authenticated;
grant update (is_favorite) on public.generations to authenticated;

-- guest_sessions: nothing — server only (migration 0005).

drop policy "users can insert own generations" on public.generations;

create policy "users can insert own generations"
  on public.generations for insert
  to authenticated
  with check (auth.uid() = user_id and guest_session_id is null);

-- A trigger function (migration 0009) — never meant to be called directly.
revoke all on function public.handle_new_user() from public, anon, authenticated;

-- ---------- migrations/0020_foreign_key_indexes.sql ----------
-- Phase 2 (database): the three foreign keys the Performance Advisor
-- reports without a covering index (lint 0001_unindexed_foreign_keys).
-- Without them, deleting a company profile or a template (ON DELETE SET
-- NULL on generations) or a plan has to scan the whole referencing table.

create index generations_company_profile_id_idx on public.generations(company_profile_id);
create index generations_template_id_idx on public.generations(template_id);
create index subscriptions_plan_id_idx on public.subscriptions(plan_id);

-- ---------- migrations/0021_generation_usage.sql ----------
-- Phase 4: what each generation cost and how long it took — the numbers
-- plan pricing is set from (README.md → "Cost and speed of generations").
-- Tokens as the provider reports them (Claude bills thinking as output, and
-- output_tokens already includes it); duration of the AI call in
-- milliseconds. Null on rows saved before this migration.
--
-- Client privileges are unchanged (migration 0019): users can read these
-- on their own rows and never update them.

alter table public.generations
  add column input_tokens integer,
  add column output_tokens integer,
  add column duration_ms integer;

-- ---------- migrations/0022_feedback.sql ----------
-- Phase 5: in-app feedback (app/(auth)/feedback). What signed-in people
-- write to us, read by the team with SQL (README.md → "Closed beta").
--
-- Server only, like guest_sessions: the page's server action checks the
-- user, validates the message and inserts with the service role, so
-- clients hold no privileges here and there is no policy to get wrong.
-- Deleting an account deletes its feedback (Privacy Policy).

create table public.feedback (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

-- Covers the foreign key and the per-user rate limit's lookup
-- (app/(auth)/feedback/actions.ts).
create index feedback_user_id_created_at_idx on public.feedback (user_id, created_at desc);

alter table public.feedback enable row level security;

revoke all on table public.feedback from anon, authenticated;

-- ---------- migrations/0023_rls_auth_uid_once.sql ----------
-- Phase 5 (performance): owner policies read auth.uid() once per query,
-- not once per row.
--
-- Written as `auth.uid() = user_id`, Postgres calls auth.uid() for every
-- row it checks — on History and the Dashboard that is every generation
-- the query scans. Wrapped in a sub-select it runs once and is reused
-- (Supabase Performance Advisor, lint `auth_rls_initplan`, which flagged
-- all ten of these; docs: "Call functions with select"). Same rules, same
-- rows: supabase/tests/rls.test.sql checks them unchanged.

alter policy "users can view own row" on public.users
  using ((select auth.uid()) = id);

alter policy "users can view own company profiles" on public.company_profiles
  using ((select auth.uid()) = user_id);
alter policy "users can insert own company profiles" on public.company_profiles
  with check ((select auth.uid()) = user_id);
alter policy "users can update own company profiles" on public.company_profiles
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
alter policy "users can delete own company profiles" on public.company_profiles
  using ((select auth.uid()) = user_id);

alter policy "users can view own usage" on public.usage_counters
  using ((select auth.uid()) = user_id);

alter policy "users can view own subscription" on public.subscriptions
  using ((select auth.uid()) = user_id);

alter policy "users can view own generations" on public.generations
  using ((select auth.uid()) = user_id);
alter policy "users can insert own generations" on public.generations
  with check ((select auth.uid()) = user_id and guest_session_id is null);
alter policy "users can update own generations" on public.generations
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- ---------- migrations/0024_billing.sql ----------
-- Phase 6 (payments, Stripe). A user's plan comes from one place: their
-- subscription rows. Only the server writes them — the Stripe webhook
-- (app/api/stripe/webhook) and the nightly reconciliation
-- (app/api/cron/reconcile-subscriptions), both re-reading the
-- subscription from Stripe — and the plan in force is the best one among
-- the rows that are `active` or `trialing` (lib/generation/plan.ts). The
-- Free row every account gets at sign-up (migration 0009) stays as the
-- floor: a canceled, unpaid or past-due paid subscription leaves Free.

-- Stripe's own subscription statuses, and what the billing page shows.
alter table public.subscriptions drop constraint subscriptions_status_check;
alter table public.subscriptions add constraint subscriptions_status_check
  check (status in ('active', 'trialing', 'past_due', 'canceled', 'unpaid',
                    'incomplete', 'incomplete_expired', 'paused'));
alter table public.subscriptions
  add column cancel_at_period_end boolean not null default false,
  add column trial_end timestamptz;
-- provider_ref is Stripe's subscription id: one row per subscription,
-- upserted by it. The Free rows have none (unique allows many nulls).
alter table public.subscriptions
  add constraint subscriptions_provider_ref_key unique (provider_ref);

-- users.plan_id was the plan before subscriptions were real, and would
-- now be a second, stale answer to "which plan is this user on".
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan_id uuid;
begin
  insert into public.users (id, email) values (new.id, new.email);

  select id into v_plan_id from public.plans where slug = 'free' limit 1;
  if v_plan_id is not null then
    insert into public.subscriptions (user_id, plan_id, status)
    values (new.id, v_plan_id, 'active');
  end if;

  return new;
end;
$$;

alter table public.users drop column plan_id;

-- Which Stripe customer is which user: created at the first checkout,
-- reused for every later one and for the Customer Portal.
create table public.billing_customers (
  user_id uuid primary key references public.users(id) on delete cascade,
  stripe_customer_id text not null unique,
  created_at timestamptz not null default now()
);

-- Webhook events already handled, by Stripe's event id: a redelivered
-- event is acknowledged without being applied again.
create table public.stripe_events (
  id text primary key,
  type text not null,
  created_at timestamptz not null default now()
);

-- One row per nightly reconciliation run: how many subscriptions were
-- compared with Stripe and how many had to be corrected.
create table public.billing_reconciliations (
  id uuid primary key default extensions.gen_random_uuid(),
  checked integer not null,
  fixed integer not null,
  created_at timestamptz not null default now()
);

-- Server only, like feedback (migration 0022): no client privileges,
-- no policies.
alter table public.billing_customers enable row level security;
alter table public.stripe_events enable row level security;
alter table public.billing_reconciliations enable row level security;
revoke all on table public.billing_customers, public.stripe_events, public.billing_reconciliations
  from anon, authenticated;

